[build]

  base = "."
  publish = "./packages/components/storybook-static"
  command = "yarn && yarn bootstrap --scope=puppies-components && yarn lerna -- exec yarn build:docs --scope=puppies-components"
