name: Tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    container: lironavon/docker-puppeteer-container:16.10.0
    steps:
        # - name: Bump version
        # env:
        #   NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        # run: |
        #   npm run release
        #   git remote rm origin
        #   git remote add origin https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/project/liron-navon/puppies.git
        #   git remote -v # for debug only 
        #   git show-ref # for debug only 

      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: fetch shallow git history
        run: git fetch --no-tags --prune --depth=1 origin +refs/heads/master:refs/remotes/origin/master
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: install base dependencies
        run: yarn install
      - name: bootstrap monorepo
        run: yarn bootstrap
      - name: build packages
        run: yarn build
      - name: test packages
        run: yarn test:ci








        

    # name: Test
    # runs-on: ubuntu-20.04

    # strategy:
    #   matrix:
    #     node-version: [15.x]

    #   - uses: actions/checkout@v2
    #   - name: fetch shallow git history
    #     run: git fetch --no-tags --prune --depth=1 origin +refs/heads/master:refs/remotes/origin/master

    #   - name: Use Node.js ${{ matrix.node-version }}
    #     uses: actions/setup-node@v2
    #     with:
    #       node-version: ${{ matrix.node-version }}
    #   - uses: actions/cache@v2
    #     with:
    #       path: '**/node_modules'
    #       key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    #   - name: install base dependencies
    #     uses: borales/actions-yarn@v2.3.0
    #     with:
    #       cmd: install # will run `yarn install` command
    #   - name: bootstrap monorepo
    #     uses: borales/actions-yarn@v2.3.0
    #     with:
    #       cmd: bootstrap # will run `yarn bootstrap` command
    #   - name: build packages
    #     uses: borales/actions-yarn@v2.3.0
    #     with:
    #       cmd: build # will run `build` command
    #   - name: test packages
    #     uses: borales/actions-yarn@v2.3.0
    #     with:
    #       cmd: test:ci # will run `yarn test:ci` command