name: Tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
      
      # install node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: install base dependencies
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install # will run `yarn install` command
      - name: bootstrap monorepo
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: bootstrap # will run `yarn bootstrap` command
      - name: build packages
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build # will run `build` command
      - name: test packages
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test:ci # will run `yarn test:ci` command