name: Tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
      - name: fetch shallow git history
        run: git fetch --no-tags --prune --depth=1 origin +refs/heads/master:refs/remotes/origin/master
      # install node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: install chromium for e2e tests
        run: |
            sudo apt-get update
            sudo apt-get install -y libgbm1
            sudo apt-get install chromium-browser
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: install base dependencies
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install # will run `yarn install` command
      - name: bootstrap monorepo
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: bootstrap # will run `yarn bootstrap` command
      - name: build packages
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build # will run `build` command
      - name: test packages
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test:ci # will run `yarn test:ci` command